# -*- coding: utf-8 -*-
"""Simple Calculator_Sahar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANPFp8iKnVGWzk0Ebar-jacOy8S0XZLl
"""

import math

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Invalid value for denominator, cant't divide by 0!"
    return a / b

def square(a):
    return a ** 2

def power(a, b):
    return a ** b

def sqrt(a):
    if a < 0:
        return "Cannot calculate the square root of a negative number!"
    return math.sqrt(a)
# test
def test_add():
    assert add(1, 2) == 3

def test_subtract():
    assert subtract(5, 3) == 2

def test_multiply():
    assert multiply(2, 3) == 6

def test_divide():
    assert divide(6, 3) == 2
    assert divide(5, 0) == "Invalid value for denominator, cant't divide by 0!"

def test_square():
    assert square(3) == 9

def test_power():
    assert power(2, 3) == 8

def test_sqrt():
    assert sqrt(4) == 2
    assert sqrt(-1) == "Cannot calculate the square root of a negative number!"


if __name__ == "__main__":
    test_add()
    test_subtract()
    test_multiply()
    test_divide()
    test_square()
    test_power()
    test_sqrt()
    print("All tests passed!")